package gov.nih.nci.cbiit.scimgmt.gds.domain;

// Generated Feb 21, 2016 12:03:16 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AppLookupT generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "APP_LOOKUP_T", schema = "NCI", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DISCRIMINATOR", "CODE", "ACTIVE" }))
public class AppLookupT implements java.io.Serializable {

	private long id;
	private String discriminator;
	private String code;
	private String description;
	private char active;
	private byte orderNum;
	private Date createDate;
	private String createUserId;
	private Date lastChangeDate;
	private String lastChangeUserId;
	private String applicationName;

	public AppLookupT() {
	}

	public AppLookupT(long id, String discriminator, String code,
			String description, char active, byte orderNum, Date createDate,
			String createUserId) {
		this.id = id;
		this.discriminator = discriminator;
		this.code = code;
		this.description = description;
		this.active = active;
		this.orderNum = orderNum;
		this.createDate = createDate;
		this.createUserId = createUserId;
	}

	public AppLookupT(long id, String discriminator, String code,
			String description, char active, byte orderNum, Date createDate,
			String createUserId, Date lastChangeDate, String lastChangeUserId,
			String applicationName) {
		this.id = id;
		this.discriminator = discriminator;
		this.code = code;
		this.description = description;
		this.active = active;
		this.orderNum = orderNum;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.lastChangeDate = lastChangeDate;
		this.lastChangeUserId = lastChangeUserId;
		this.applicationName = applicationName;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "DISCRIMINATOR", nullable = false, length = 90)
	public String getDiscriminator() {
		return this.discriminator;
	}

	public void setDiscriminator(String discriminator) {
		this.discriminator = discriminator;
	}

	@Column(name = "CODE", nullable = false, length = 60)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 1200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ACTIVE", nullable = false, length = 1)
	public char getActive() {
		return this.active;
	}

	public void setActive(char active) {
		this.active = active;
	}

	@Column(name = "ORDER_NUM", nullable = false, precision = 2, scale = 0)
	public byte getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(byte orderNum) {
		this.orderNum = orderNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", nullable = false, length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_USER_ID", nullable = false, length = 50)
	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHANGE_DATE", length = 7)
	public Date getLastChangeDate() {
		return this.lastChangeDate;
	}

	public void setLastChangeDate(Date lastChangeDate) {
		this.lastChangeDate = lastChangeDate;
	}

	@Column(name = "LAST_CHANGE_USER_ID", length = 50)
	public String getLastChangeUserId() {
		return this.lastChangeUserId;
	}

	public void setLastChangeUserId(String lastChangeUserId) {
		this.lastChangeUserId = lastChangeUserId;
	}

	@Column(name = "APPLICATION_NAME", length = 150)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

}
