package gov.nih.nci.cbiit.scimgmt.gds.domain;

// Generated Feb 21, 2016 12:03:16 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppPropertiesTId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class AppPropertiesTId implements java.io.Serializable {

	private String appName;
	private String propKey;

	public AppPropertiesTId() {
	}

	public AppPropertiesTId(String appName, String propKey) {
		this.appName = appName;
		this.propKey = propKey;
	}

	@Column(name = "APP_NAME", nullable = false, length = 150)
	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	@Column(name = "PROP_KEY", nullable = false, length = 90)
	public String getPropKey() {
		return this.propKey;
	}

	public void setPropKey(String propKey) {
		this.propKey = propKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppPropertiesTId))
			return false;
		AppPropertiesTId castOther = (AppPropertiesTId) other;

		return ((this.getAppName() == castOther.getAppName()) || (this
				.getAppName() != null && castOther.getAppName() != null && this
				.getAppName().equals(castOther.getAppName())))
				&& ((this.getPropKey() == castOther.getPropKey()) || (this
						.getPropKey() != null && castOther.getPropKey() != null && this
						.getPropKey().equals(castOther.getPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAppName() == null ? 0 : this.getAppName().hashCode());
		result = 37 * result
				+ (getPropKey() == null ? 0 : this.getPropKey().hashCode());
		return result;
	}

}
