package gov.nih.nci.cbiit.scimgmt.gds.domain;

// Generated Feb 21, 2016 12:03:16 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppPropertiesT generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "APP_PROPERTIES_T", schema = "NCI")
public class AppPropertiesT implements java.io.Serializable {

	private AppPropertiesTId id;
	private String propValue;
	private Date createDate;
	private Date lastChangeDate;

	public AppPropertiesT() {
	}

	public AppPropertiesT(AppPropertiesTId id, String propValue, Date createDate) {
		this.id = id;
		this.propValue = propValue;
		this.createDate = createDate;
	}

	public AppPropertiesT(AppPropertiesTId id, String propValue,
			Date createDate, Date lastChangeDate) {
		this.id = id;
		this.propValue = propValue;
		this.createDate = createDate;
		this.lastChangeDate = lastChangeDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "appName", column = @Column(name = "APP_NAME", nullable = false, length = 150)),
			@AttributeOverride(name = "propKey", column = @Column(name = "PROP_KEY", nullable = false, length = 90)) })
	public AppPropertiesTId getId() {
		return this.id;
	}

	public void setId(AppPropertiesTId id) {
		this.id = id;
	}

	@Column(name = "PROP_VALUE", nullable = false, length = 600)
	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", nullable = false, length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHANGE_DATE", length = 7)
	public Date getLastChangeDate() {
		return this.lastChangeDate;
	}

	public void setLastChangeDate(Date lastChangeDate) {
		this.lastChangeDate = lastChangeDate;
	}

}
