package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 4, 2016 12:46:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocumentsT generated by hbm2java
 */
@Entity
@Table(name = "DOCUMENTS_T")
public class DocumentsT implements java.io.Serializable {

	private Integer id;
	private InstitutionalCertificationsT institutionalCertificationsT;
	private ProjectsT projectsT;
	private String docType;
	private String fileName;
	private Date uploadedDate;
	private Integer versionNum;
	private String activeFlag;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;

	public DocumentsT() {
	}

	public DocumentsT(Integer id, InstitutionalCertificationsT institutionalCertificationsT, ProjectsT projectsT,
			String docType, Date uploadedDate, Integer versionNum, String activeFlag, Date createdDate,
			String createdBy) {
		this.id = id;
		this.institutionalCertificationsT = institutionalCertificationsT;
		this.projectsT = projectsT;
		this.docType = docType;
		this.uploadedDate = uploadedDate;
		this.versionNum = versionNum;
		this.activeFlag = activeFlag;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public DocumentsT(Integer id, InstitutionalCertificationsT institutionalCertificationsT, ProjectsT projectsT,
			String docType, String fileName, Date uploadedDate, Integer versionNum, String activeFlag,
			Date createdDate, String createdBy, Date lastChangedDate, String lastChangedBy) {
		this.id = id;
		this.institutionalCertificationsT = institutionalCertificationsT;
		this.projectsT = projectsT;
		this.docType = docType;
		this.fileName = fileName;
		this.uploadedDate = uploadedDate;
		this.versionNum = versionNum;
		this.activeFlag = activeFlag;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CERTIFICATION_ID", nullable = false)
	public InstitutionalCertificationsT getInstitutionalCertificationsT() {
		return this.institutionalCertificationsT;
	}

	public void setInstitutionalCertificationsT(InstitutionalCertificationsT institutionalCertificationsT) {
		this.institutionalCertificationsT = institutionalCertificationsT;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false)
	public ProjectsT getProjectsT() {
		return this.projectsT;
	}

	public void setProjectsT(ProjectsT projectsT) {
		this.projectsT = projectsT;
	}

	@Column(name = "DOC_TYPE", nullable = false, length = 120)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "FILE_NAME", length = 120)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPLOADED_DATE", nullable = false, length = 7)
	public Date getUploadedDate() {
		return this.uploadedDate;
	}

	public void setUploadedDate(Date uploadedDate) {
		this.uploadedDate = uploadedDate;
	}

	@Column(name = "VERSION_NUM", nullable = false, precision = 10, scale = 0)
	public Integer getVersionNum() {
		return this.versionNum;
	}

	public void setVersionNum(Integer versionNum) {
		this.versionNum = versionNum;
	}

	@Column(name = "ACTIVE_FLAG", nullable = false, length = 4)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

}
