package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 4, 2016 12:46:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DulChecklistSelectionsT generated by hbm2java
 */
@Entity
@Table(name = "DUL_CHECKLIST_SELECTIONS_T")
public class DulChecklistSelectionsT implements java.io.Serializable {

	private Integer id;
	private StudiesT studiesT;
	private DulChecklistT dulChecklistT;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;

	public DulChecklistSelectionsT() {
	}

	public DulChecklistSelectionsT(Integer id, StudiesT studiesT, DulChecklistT dulChecklistT, Date createdDate,
			String createdBy) {
		this.id = id;
		this.studiesT = studiesT;
		this.dulChecklistT = dulChecklistT;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public DulChecklistSelectionsT(Integer id, StudiesT studiesT, DulChecklistT dulChecklistT, Date createdDate,
			String createdBy, Date lastChangedDate, String lastChangedBy) {
		this.id = id;
		this.studiesT = studiesT;
		this.dulChecklistT = dulChecklistT;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUDY_ID", nullable = false)
	public StudiesT getStudiesT() {
		return this.studiesT;
	}

	public void setStudiesT(StudiesT studiesT) {
		this.studiesT = studiesT;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DUL_ID", nullable = false)
	public DulChecklistT getDulChecklistT() {
		return this.dulChecklistT;
	}

	public void setDulChecklistT(DulChecklistT dulChecklistT) {
		this.dulChecklistT = dulChecklistT;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

}
