package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 4, 2016 12:46:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DulChecklist generated by hbm2java
 */
@Entity
@Table(name = "DUL_CHECKLIST_T")
public class DulChecklist implements java.io.Serializable {

	private Long id;
	private Long parentDulId;
	private String displayText;
	private Long displayOrderNum;
	private String activeFlag;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;
	private Set<DulChecklistSelection> dulChecklistSelections = new HashSet(0);

	public DulChecklist() {
	}

	public DulChecklist(Long id, String displayText, Long displayOrderNum, String activeFlag, Date createdDate,
			String createdBy) {
		this.id = id;
		this.displayText = displayText;
		this.displayOrderNum = displayOrderNum;
		this.activeFlag = activeFlag;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public DulChecklist(Long id, Long parentDulId, String displayText, Long displayOrderNum,
			String activeFlag, Date createdDate, String createdBy, Date lastChangedDate, String lastChangedBy,
			Set dulChecklistSelections) {
		this.id = id;
		this.parentDulId = parentDulId;
		this.displayText = displayText;
		this.displayOrderNum = displayOrderNum;
		this.activeFlag = activeFlag;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
		this.dulChecklistSelections = dulChecklistSelections;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PARENT_DUL_ID", precision = 10, scale = 0)
	public Long getParentDulId() {
		return this.parentDulId;
	}

	public void setParentDulId(Long parentDulId) {
		this.parentDulId = parentDulId;
	}

	@Column(name = "DISPLAY_TEXT", nullable = false, length = 120)
	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	@Column(name = "DISPLAY_ORDER_NUM", nullable = false, precision = 10, scale = 0)
	public Long getDisplayOrderNum() {
		return this.displayOrderNum;
	}

	public void setDisplayOrderNum(Long displayOrderNum) {
		this.displayOrderNum = displayOrderNum;
	}

	@Column(name = "ACTIVE_FLAG", nullable = false, length = 4)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dulChecklist")
	public Set<DulChecklistSelection> getDulChecklistSelections() {
		return this.dulChecklistSelections;
	}

	public void setDulChecklistSelections(Set<DulChecklistSelection> dulChecklistSelections) {
		this.dulChecklistSelections = dulChecklistSelections;
	}

}
