package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Dec 12, 2016 6:44:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailNotification generated by hbm2java
 */
@Entity
@Table(name = "EMAIL_NOTIFICATIONS_T")
public class EmailNotification implements java.io.Serializable {

	private Long id;
	private Long mailTemplateId;
	private String toList;
	private Date sentDate;
	private String docAbbreviation;
	private Long projectId;

	public EmailNotification() {
	}

	public EmailNotification(Long id) {
		this.id = id;
	}

	public EmailNotification(Long id, Long mailTemplateId, String toList, Date sentDate,
			String docAbbreviation, Long projectId) {
		this.id = id;
		this.mailTemplateId = mailTemplateId;
		this.toList = toList;
		this.sentDate = sentDate;
		this.docAbbreviation = docAbbreviation;
		this.projectId = projectId;
	}

	@Id
	@SequenceGenerator(name="enot_seq_gen", sequenceName="ENOT_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "enot_seq_gen")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "MAIL_TEMPLATE_ID", precision = 10, scale = 0)
	public Long getMailTemplateId() {
		return this.mailTemplateId;
	}

	public void setMailTemplateId(Long mailTemplateId) {
		this.mailTemplateId = mailTemplateId;
	}

	@Column(name = "TO_LIST", length = 800)
	public String getToList() {
		return this.toList;
	}

	public void setToList(String toList) {
		this.toList = toList;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SENT_DATE", length = 7)
	public Date getSentDate() {
		return this.sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

	@Column(name = "DOC_ABBREVIATION", length = 120)
	public String getDocAbbreviation() {
		return this.docAbbreviation;
	}

	public void setDocAbbreviation(String docAbbreviation) {
		this.docAbbreviation = docAbbreviation;
	}

	@Column(name = "PROJECT_ID", precision = 10, scale = 0)
	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

}
