package gov.nih.nci.cbiit.scimgmt.gds.domain;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "MESSAGES_T", schema = "GDS")
public class HelpText implements java.io.Serializable {

	private String messageKey;
	private String messageValue;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;

	public HelpText() {
	}

	public HelpText(String messageKey, String messageValue, Date createdDate,
			String createdBy) {
		this.messageKey = messageKey;
		this.messageValue = messageValue;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public HelpText(String messageKey, String messageValue, Date createdDate,
			String createdBy, Date lastChangedDate, String lastChangedBy) {
		this.messageKey = messageKey;
		this.messageValue = messageValue;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
	}

	@Id
	@Column(name = "MESSAGE_KEY", unique = true, nullable = false, length = 120)
	public String getMessageKey() {
		return messageKey;
	}

	public void setMessageKey(String messageKey) {
		this.messageKey = messageKey;
	}

	@Column(name = "MESSAGE_VALUE", nullable = false, length = 2000)
	public String getMessageValue() {
		return messageValue;
	}

	public void setMessageValue(String messageValue) {
		this.messageValue = messageValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

}
