package gov.nih.nci.cbiit.scimgmt.gds.domain;

// Generated Feb 26, 2016 2:29:04 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LookupT generated by hbm2java
 */
@Entity
@Table(name = "LOOKUP_T", schema = "GDS")
public class LookupT implements java.io.Serializable {

	@Id
	private long id;
	private String code;
	@Override
	public String toString() {
		return "LookupT [id=" + id + ", code=" + code + ", displayName=" + displayName + ", description=" + description
				+ ", createdDate=" + createdDate + ", createdBy=" + createdBy + ", lastChangedDate=" + lastChangedDate
				+ ", lastChangedBy=" + lastChangedBy + "]";
	}

	private String displayName;
	private String description;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;

	public LookupT() {
	}

	public LookupT(long id, String code, Date createdDate, String createdBy) {
		this.id = id;
		this.code = code;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public LookupT(long id, String code, String displayName,
			String description, Date createdDate, String createdBy,
			Date lastChangedDate, String lastChangedBy) {
		this.id = id;
		this.code = code;
		this.displayName = displayName;
		this.description = description;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CODE", nullable = false, length = 40)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "DISPLAY_NAME", length = 120)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "DESCRIPTION", length = 120)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

}
