package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 3, 2016 3:28:59 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.WordUtils;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Type;

/**
 * NedPerson generated by hbm2java
 */
@Entity
@Table(name = "NED_PERSON", schema = "NED_LOCAL")
public class NedPerson implements java.io.Serializable {

	private String nedId;
	private Long id;
	private String firstName;
	private String building;
	private String c;
	private String description;
	private String facsimiletelephone;
	private String generationqualif;
	private String initials;
	private String l;
	private String email;
	private String manager;
	private String middlename;
	private String mobiletelephonenum;
	private String nihbadgetitle;
	private String nihcommongenqualif;
	private String preferredName;
	private String nihcommonmiddlenam;
	private String nihcommonsn;
	private Date nihcreatetimestamp;
	private String nihcreatorsname;
	private String nihdeliveryaddress;
	private Date nihdirentryeffectivedate;
	private Date nihdirentryexpirationdate;
	private String nihdirentrynoprint;
	private String nihdirentryunlist;
	private String nihhhsuniquemail;
	private Date nihidbadgeexpdate;
	private String nihidbadgeissuerea;
	private Date nihidbadgereqdate;
	private String nihipd;
	private String nihlibraryauth;
	private String nihmailstop;
	private String adUserId;
	private String nihmdslinktohelp;
	private String nihmdslinktoph;
	private String nihmixcasecommonsn;
	private String lastName;
	private String nihmodifiersname;
	private Date nihmodifytimestamp;
	private String nihorgacronym;
	private String nihorgname;
	private String orgpath;
	private String nihouacronym;
	private String nihouname;
	private String nihphysicaladdress;
	private String nihphyspostalcode;
	private String nihsac;
	private String nihsite;
	private String nihssodomain;
	private String nihssousername;
	private String nihsuffixqualifier;
	private String nihsummerstatus;
	private String nihtty;
	private Boolean nihuidquality;
	private Date nihuidvalidationts;
	private String nihuidvalidator;
	private String nihuniquemail;
	private String orgStatus;
	private String pagertelephonenum;
	private String personaltitle;
	private String postaladdress;
	private String postalcode;
	private String room;
	private String secretary;
	private String st;
	private String street;
	private String phone;
	private String title;
	private String nihprimarysmtp;
	private String nihdupuid;
	private String nihidbadgeless6mos;
	private String nihnomiddlename;
	private Date nihidbadgereqexpdt;
	private String nihidbadgereqtype;
	private String nihpoc;
	private Date inactiveDate;
	private Date createdDate;
	
	private PersonRole personRole;
	//private UserRole userRole;

	public NedPerson() {
	}

	public NedPerson(Long id, String nedId, String firstName, Date createdDate) {
		this.id = id;
		this.nedId = nedId;
		this.firstName = firstName;
		this.createdDate = createdDate;
	}

	public NedPerson(Long id, String nedId, String building, String c, String description,
			String facsimiletelephone, String generationqualif, String firstName, String initials, String l,
			String email, String manager, String middlename, String mobiletelephonenum, String nihbadgetitle,
			String nihcommongenqualif, String preferredName, String nihcommonmiddlenam, String nihcommonsn,
			Date nihcreatetimestamp, String nihcreatorsname, String nihdeliveryaddress, Date nihdirentryeffectivedate,
			Date nihdirentryexpirationdate, String nihdirentrynoprint, String nihdirentryunlist,
			String nihhhsuniquemail, Date nihidbadgeexpdate, String nihidbadgeissuerea, Date nihidbadgereqdate,
			String nihipd, String nihlibraryauth, String nihmailstop, String adUserId,
			String nihmdslinktohelp, String nihmdslinktoph, String nihmixcasecommonsn, String lastName,
			String nihmodifiersname, Date nihmodifytimestamp, String nihorgacronym, String nihorgname,
			String orgpath, String nihouacronym, String nihouname, String nihphysicaladdress,
			String nihphyspostalcode, String nihsac, String nihsite, String nihssodomain, String nihssousername,
			String nihsuffixqualifier, String nihsummerstatus, String nihtty, Boolean nihuidquality,
			Date nihuidvalidationts, String nihuidvalidator, String nihuniquemail, String orgStatus,
			String pagertelephonenum, String personaltitle, String postaladdress, String postalcode, String room,
			String secretary, String st, String street, String phone, String title,
			String nihprimarysmtp, String nihdupuid, String nihidbadgeless6mos, String nihnomiddlename,
			Date nihidbadgereqexpdt, String nihidbadgereqtype, String nihpoc,
			Date inactiveDate,
			Date createdDate) {
		this.id = id;
		this.building = building;
		this.c = c;
		this.description = description;
		this.facsimiletelephone = facsimiletelephone;
		this.generationqualif = generationqualif;
		this.firstName = firstName;
		this.initials = initials;
		this.l = l;
		this.email = email;
		this.manager = manager;
		this.middlename = middlename;
		this.mobiletelephonenum = mobiletelephonenum;
		this.nihbadgetitle = nihbadgetitle;
		this.nihcommongenqualif = nihcommongenqualif;
		this.preferredName = preferredName;
		this.nihcommonmiddlenam = nihcommonmiddlenam;
		this.nihcommonsn = nihcommonsn;
		this.nihcreatetimestamp = nihcreatetimestamp;
		this.nihcreatorsname = nihcreatorsname;
		this.nihdeliveryaddress = nihdeliveryaddress;
		this.nihdirentryeffectivedate = nihdirentryeffectivedate;
		this.nihdirentryexpirationdate = nihdirentryexpirationdate;
		this.nihdirentrynoprint = nihdirentrynoprint;
		this.nihdirentryunlist = nihdirentryunlist;
		this.nihhhsuniquemail = nihhhsuniquemail;
		this.nihidbadgeexpdate = nihidbadgeexpdate;
		this.nihidbadgeissuerea = nihidbadgeissuerea;
		this.nihidbadgereqdate = nihidbadgereqdate;
		this.nihipd = nihipd;
		this.nihlibraryauth = nihlibraryauth;
		this.nihmailstop = nihmailstop;
		this.adUserId = adUserId;
		this.nihmdslinktohelp = nihmdslinktohelp;
		this.nihmdslinktoph = nihmdslinktoph;
		this.nihmixcasecommonsn = nihmixcasecommonsn;
		this.lastName = lastName;
		this.nihmodifiersname = nihmodifiersname;
		this.nihmodifytimestamp = nihmodifytimestamp;
		this.nihorgacronym = nihorgacronym;
		this.nihorgname = nihorgname;
		this.orgpath = orgpath;
		this.nihouacronym = nihouacronym;
		this.nihouname = nihouname;
		this.nihphysicaladdress = nihphysicaladdress;
		this.nihphyspostalcode = nihphyspostalcode;
		this.nihsac = nihsac;
		this.nihsite = nihsite;
		this.nihssodomain = nihssodomain;
		this.nihssousername = nihssousername;
		this.nihsuffixqualifier = nihsuffixqualifier;
		this.nihsummerstatus = nihsummerstatus;
		this.nihtty = nihtty;
		this.nihuidquality = nihuidquality;
		this.nihuidvalidationts = nihuidvalidationts;
		this.nihuidvalidator = nihuidvalidator;
		this.nihuniquemail = nihuniquemail;
		this.orgStatus = orgStatus;
		this.pagertelephonenum = pagertelephonenum;
		this.personaltitle = personaltitle;
		this.postaladdress = postaladdress;
		this.postalcode = postalcode;
		this.room = room;
		this.secretary = secretary;
		this.st = st;
		this.street = street;
		this.phone = phone;
		this.title = title;
		this.nihprimarysmtp = nihprimarysmtp;
		this.nihdupuid = nihdupuid;
		this.nihidbadgeless6mos = nihidbadgeless6mos;
		this.nihnomiddlename = nihnomiddlename;
		this.nihidbadgereqexpdt = nihidbadgereqexpdt;
		this.nihidbadgereqtype = nihidbadgereqtype;
		this.nihpoc = nihpoc;
		this.inactiveDate = inactiveDate;
		this.createdDate = createdDate;
	}

	@Id
	@Column(name = "UNIQUEIDENTIFIER", nullable = false, length = 30)
	public String getNedId() {
		return this.nedId;
	}

	public void setNedId(String nedId) {
		this.nedId = nedId;
	}
	
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "BUILDINGNAME", length = 768)
	public String getBuilding() {
		return this.building;
	}

	public void setBuilding(String building) {
		this.building = building;
	}

	@Column(name = "C", length = 6)
	public String getC() {
		return this.c;
	}

	public void setC(String c) {
		this.c = c;
	}

	@Column(name = "DESCRIPTION", length = 3072)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "FACSIMILETELEPHONE", length = 90)
	public String getFacsimiletelephone() {
		return this.facsimiletelephone;
	}

	public void setFacsimiletelephone(String facsimiletelephone) {
		this.facsimiletelephone = facsimiletelephone;
	}

	@Column(name = "GENERATIONQUALIF", length = 15)
	public String getGenerationqualif() {
		return this.generationqualif;
	}

	public void setGenerationqualif(String generationqualif) {
		this.generationqualif = generationqualif;
	}

	@Column(name = "GIVENNAME", nullable = false, length = 192)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "INITIALS", length = 15)
	public String getInitials() {
		return this.initials;
	}

	public void setInitials(String initials) {
		this.initials = initials;
	}

	@Column(name = "L", length = 384)
	public String getL() {
		return this.l;
	}

	public void setL(String l) {
		this.l = l;
	}

	@Column(name = "MAIL", length = 256)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MANAGER", length = 30)
	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	@Column(name = "MIDDLENAME", length = 192)
	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	@Column(name = "MOBILETELEPHONENUM", length = 90)
	public String getMobiletelephonenum() {
		return this.mobiletelephonenum;
	}

	public void setMobiletelephonenum(String mobiletelephonenum) {
		this.mobiletelephonenum = mobiletelephonenum;
	}

	@Column(name = "NIHBADGETITLE", length = 120)
	public String getNihbadgetitle() {
		return this.nihbadgetitle;
	}

	public void setNihbadgetitle(String nihbadgetitle) {
		this.nihbadgetitle = nihbadgetitle;
	}

	@Column(name = "NIHCOMMONGENQUALIF", length = 15)
	public String getNihcommongenqualif() {
		return this.nihcommongenqualif;
	}

	public void setNihcommongenqualif(String nihcommongenqualif) {
		this.nihcommongenqualif = nihcommongenqualif;
	}

	@Column(name = "NIHCOMMONGIVENNAME", length = 192)
	public String getPreferredName() {
		return this.preferredName;
	}

	public void setPreferredName(String preferredName) {
		this.preferredName = preferredName;
	}

	@Column(name = "NIHCOMMONMIDDLENAM", length = 192)
	public String getNihcommonmiddlenam() {
		return this.nihcommonmiddlenam;
	}

	public void setNihcommonmiddlenam(String nihcommonmiddlenam) {
		this.nihcommonmiddlenam = nihcommonmiddlenam;
	}

	@Column(name = "NIHCOMMONSN", length = 192)
	public String getNihcommonsn() {
		return this.nihcommonsn;
	}

	public void setNihcommonsn(String nihcommonsn) {
		this.nihcommonsn = nihcommonsn;
	}

	@Column(name = "NIHCREATETIMESTAMP", length = 7)
	public Date getNihcreatetimestamp() {
		return this.nihcreatetimestamp;
	}

	public void setNihcreatetimestamp(Date nihcreatetimestamp) {
		this.nihcreatetimestamp = nihcreatetimestamp;
	}

	@Column(name = "NIHCREATORSNAME", length = 30)
	public String getNihcreatorsname() {
		return this.nihcreatorsname;
	}

	public void setNihcreatorsname(String nihcreatorsname) {
		this.nihcreatorsname = nihcreatorsname;
	}

	@Column(name = "NIHDELIVERYADDRESS", length = 765)
	public String getNihdeliveryaddress() {
		return this.nihdeliveryaddress;
	}

	public void setNihdeliveryaddress(String nihdeliveryaddress) {
		this.nihdeliveryaddress = nihdeliveryaddress;
	}

	@Column(name = "NIHDIRENTRYEFFECTIVEDATE", length = 7)
	public Date getNihdirentryeffectivedate() {
		return this.nihdirentryeffectivedate;
	}

	public void setNihdirentryeffectivedate(Date nihdirentryeffectivedate) {
		this.nihdirentryeffectivedate = nihdirentryeffectivedate;
	}

	@Column(name = "NIHDIRENTRYEXPIRATIONDATE", length = 7)
	public Date getNihdirentryexpirationdate() {
		return this.nihdirentryexpirationdate;
	}

	public void setNihdirentryexpirationdate(Date nihdirentryexpirationdate) {
		this.nihdirentryexpirationdate = nihdirentryexpirationdate;
	}

	@Column(name = "NIHDIRENTRYNOPRINT", length = 3)
	public String getNihdirentrynoprint() {
		return this.nihdirentrynoprint;
	}

	public void setNihdirentrynoprint(String nihdirentrynoprint) {
		this.nihdirentrynoprint = nihdirentrynoprint;
	}

	@Column(name = "NIHDIRENTRYUNLIST", length = 3)
	public String getNihdirentryunlist() {
		return this.nihdirentryunlist;
	}

	public void setNihdirentryunlist(String nihdirentryunlist) {
		this.nihdirentryunlist = nihdirentryunlist;
	}

	@Column(name = "NIHHHSUNIQUEMAIL", length = 765)
	public String getNihhhsuniquemail() {
		return this.nihhhsuniquemail;
	}

	public void setNihhhsuniquemail(String nihhhsuniquemail) {
		this.nihhhsuniquemail = nihhhsuniquemail;
	}

	@Column(name = "NIHIDBADGEEXPDATE", length = 7)
	public Date getNihidbadgeexpdate() {
		return this.nihidbadgeexpdate;
	}

	public void setNihidbadgeexpdate(Date nihidbadgeexpdate) {
		this.nihidbadgeexpdate = nihidbadgeexpdate;
	}

	@Column(name = "NIHIDBADGEISSUEREA", length = 60)
	public String getNihidbadgeissuerea() {
		return this.nihidbadgeissuerea;
	}

	public void setNihidbadgeissuerea(String nihidbadgeissuerea) {
		this.nihidbadgeissuerea = nihidbadgeissuerea;
	}

	@Column(name = "NIHIDBADGEREQDATE", length = 7)
	public Date getNihidbadgereqdate() {
		return this.nihidbadgereqdate;
	}

	public void setNihidbadgereqdate(Date nihidbadgereqdate) {
		this.nihidbadgereqdate = nihidbadgereqdate;
	}

	@Column(name = "NIHIPD", length = 144)
	public String getNihipd() {
		return this.nihipd;
	}

	public void setNihipd(String nihipd) {
		this.nihipd = nihipd;
	}

	@Column(name = "NIHLIBRARYAUTH", length = 3)
	public String getNihlibraryauth() {
		return this.nihlibraryauth;
	}

	public void setNihlibraryauth(String nihlibraryauth) {
		this.nihlibraryauth = nihlibraryauth;
	}

	@Column(name = "NIHMAILSTOP", length = 120)
	public String getNihmailstop() {
		return this.nihmailstop;
	}

	public void setNihmailstop(String nihmailstop) {
		this.nihmailstop = nihmailstop;
	}

	@Column(name = "NIHMDSLINKTOADNIH", length = 60)
	public String getAdUserId() {
		return this.adUserId;
	}

	public void setAdUserId(String adUserId) {
		this.adUserId = adUserId;
	}

	@Column(name = "NIHMDSLINKTOHELP", length = 36)
	public String getNihmdslinktohelp() {
		return this.nihmdslinktohelp;
	}

	public void setNihmdslinktohelp(String nihmdslinktohelp) {
		this.nihmdslinktohelp = nihmdslinktohelp;
	}

	@Column(name = "NIHMDSLINKTOPH", length = 96)
	public String getNihmdslinktoph() {
		return this.nihmdslinktoph;
	}

	public void setNihmdslinktoph(String nihmdslinktoph) {
		this.nihmdslinktoph = nihmdslinktoph;
	}

	@Column(name = "NIHMIXCASECOMMONSN", length = 192)
	public String getNihmixcasecommonsn() {
		return this.nihmixcasecommonsn;
	}

	public void setNihmixcasecommonsn(String nihmixcasecommonsn) {
		this.nihmixcasecommonsn = nihmixcasecommonsn;
	}

	@Column(name = "NIHMIXCASESN", length = 192)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "NIHMODIFIERSNAME", length = 30)
	public String getNihmodifiersname() {
		return this.nihmodifiersname;
	}

	public void setNihmodifiersname(String nihmodifiersname) {
		this.nihmodifiersname = nihmodifiersname;
	}

	@Column(name = "NIHMODIFYTIMESTAMP", length = 7)
	public Date getNihmodifytimestamp() {
		return this.nihmodifytimestamp;
	}

	public void setNihmodifytimestamp(Date nihmodifytimestamp) {
		this.nihmodifytimestamp = nihmodifytimestamp;
	}

	@Column(name = "NIHORGACRONYM", length = 192)
	public String getNihorgacronym() {
		return this.nihorgacronym;
	}

	public void setNihorgacronym(String nihorgacronym) {
		this.nihorgacronym = nihorgacronym;
	}

	@Column(name = "NIHORGNAME", length = 192)
	public String getNihorgname() {
		return this.nihorgname;
	}

	public void setNihorgname(String nihorgname) {
		this.nihorgname = nihorgname;
	}

	@Column(name = "NIHORGPATH", length = 768)
	public String getOrgpath() {
		return this.orgpath;
	}

	public void setOrgpath(String orgpath) {
		this.orgpath = orgpath;
	}

	@Column(name = "NIHOUACRONYM", length = 192)
	public String getNihouacronym() {
		return this.nihouacronym;
	}

	public void setNihouacronym(String nihouacronym) {
		this.nihouacronym = nihouacronym;
	}

	@Column(name = "NIHOUNAME", length = 192)
	public String getNihouname() {
		return this.nihouname;
	}

	public void setNihouname(String nihouname) {
		this.nihouname = nihouname;
	}

	@Column(name = "NIHPHYSICALADDRESS", length = 765)
	public String getNihphysicaladdress() {
		return this.nihphysicaladdress;
	}

	public void setNihphysicaladdress(String nihphysicaladdress) {
		this.nihphysicaladdress = nihphysicaladdress;
	}

	@Column(name = "NIHPHYSPOSTALCODE", length = 120)
	public String getNihphyspostalcode() {
		return this.nihphyspostalcode;
	}

	public void setNihphyspostalcode(String nihphyspostalcode) {
		this.nihphyspostalcode = nihphyspostalcode;
	}

	@Column(name = "NIHSAC", length = 90)
	public String getNihsac() {
		return this.nihsac;
	}

	public void setNihsac(String nihsac) {
		this.nihsac = nihsac;
	}

	@Column(name = "NIHSITE", length = 45)
	public String getNihsite() {
		return this.nihsite;
	}

	public void setNihsite(String nihsite) {
		this.nihsite = nihsite;
	}

	@Column(name = "NIHSSODOMAIN", length = 45)
	public String getNihssodomain() {
		return this.nihssodomain;
	}

	public void setNihssodomain(String nihssodomain) {
		this.nihssodomain = nihssodomain;
	}

	@Column(name = "NIHSSOUSERNAME", length = 60)
	public String getNihssousername() {
		return this.nihssousername;
	}

	public void setNihssousername(String nihssousername) {
		this.nihssousername = nihssousername;
	}

	@Column(name = "NIHSUFFIXQUALIFIER", length = 60)
	public String getNihsuffixqualifier() {
		return this.nihsuffixqualifier;
	}

	public void setNihsuffixqualifier(String nihsuffixqualifier) {
		this.nihsuffixqualifier = nihsuffixqualifier;
	}

	@Column(name = "NIHSUMMERSTATUS", length = 3)
	public String getNihsummerstatus() {
		return this.nihsummerstatus;
	}

	public void setNihsummerstatus(String nihsummerstatus) {
		this.nihsummerstatus = nihsummerstatus;
	}

	@Column(name = "NIHTTY", length = 90)
	public String getNihtty() {
		return this.nihtty;
	}

	public void setNihtty(String nihtty) {
		this.nihtty = nihtty;
	}

	@Type(type="yes_no")
	@Column(name = "NIHUIDQUALITY")
	public Boolean getNihuidquality() {
		return this.nihuidquality;
	}

	public void setNihuidquality(Boolean nihuidquality) {
		this.nihuidquality = nihuidquality;
	}

	@Column(name = "NIHUIDVALIDATIONTS", length = 7)
	public Date getNihuidvalidationts() {
		return this.nihuidvalidationts;
	}

	public void setNihuidvalidationts(Date nihuidvalidationts) {
		this.nihuidvalidationts = nihuidvalidationts;
	}

	@Column(name = "NIHUIDVALIDATOR", length = 30)
	public String getNihuidvalidator() {
		return this.nihuidvalidator;
	}

	public void setNihuidvalidator(String nihuidvalidator) {
		this.nihuidvalidator = nihuidvalidator;
	}

	@Column(name = "NIHUNIQUEMAIL", length = 768)
	public String getNihuniquemail() {
		return this.nihuniquemail;
	}

	public void setNihuniquemail(String nihuniquemail) {
		this.nihuniquemail = nihuniquemail;
	}

	@Column(name = "ORGANIZATIONALSTAT", length = 768)
	public String getOrgStatus() {
		return this.orgStatus;
	}

	public void setOrgStatus(String orgStatus) {
		this.orgStatus = orgStatus;
	}

	@Column(name = "PAGERTELEPHONENUM", length = 90)
	public String getPagertelephonenum() {
		return this.pagertelephonenum;
	}

	public void setPagertelephonenum(String pagertelephonenum) {
		this.pagertelephonenum = pagertelephonenum;
	}

	@Column(name = "PERSONALTITLE", length = 48)
	public String getPersonaltitle() {
		return this.personaltitle;
	}

	public void setPersonaltitle(String personaltitle) {
		this.personaltitle = personaltitle;
	}

	@Column(name = "POSTALADDRESS", length = 765)
	public String getPostaladdress() {
		return this.postaladdress;
	}

	public void setPostaladdress(String postaladdress) {
		this.postaladdress = postaladdress;
	}

	@Column(name = "POSTALCODE", length = 120)
	public String getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	@Column(name = "ROOMNUMBER", length = 768)
	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	@Column(name = "SECRETARY", length = 30)
	public String getSecretary() {
		return this.secretary;
	}

	public void setSecretary(String secretary) {
		this.secretary = secretary;
	}

	@Column(name = "ST", length = 384)
	public String getSt() {
		return this.st;
	}

	public void setSt(String st) {
		this.st = st;
	}

	@Column(name = "STREET", length = 384)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "TELEPHONENUMBER", length = 90)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "TITLE", length = 192)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "NIHPRIMARYSMTP", length = 768)
	public String getNihprimarysmtp() {
		return this.nihprimarysmtp;
	}

	public void setNihprimarysmtp(String nihprimarysmtp) {
		this.nihprimarysmtp = nihprimarysmtp;
	}

	@Column(name = "NIHDUPUID", length = 765)
	public String getNihdupuid() {
		return this.nihdupuid;
	}

	public void setNihdupuid(String nihdupuid) {
		this.nihdupuid = nihdupuid;
	}

	@Column(name = "NIHIDBADGELESS6MOS", length = 3)
	public String getNihidbadgeless6mos() {
		return this.nihidbadgeless6mos;
	}

	public void setNihidbadgeless6mos(String nihidbadgeless6mos) {
		this.nihidbadgeless6mos = nihidbadgeless6mos;
	}

	@Column(name = "NIHNOMIDDLENAME", length = 3)
	public String getNihnomiddlename() {
		return this.nihnomiddlename;
	}

	public void setNihnomiddlename(String nihnomiddlename) {
		this.nihnomiddlename = nihnomiddlename;
	}

	@Column(name = "NIHIDBADGEREQEXPDT", length = 7)
	public Date getNihidbadgereqexpdt() {
		return this.nihidbadgereqexpdt;
	}

	public void setNihidbadgereqexpdt(Date nihidbadgereqexpdt) {
		this.nihidbadgereqexpdt = nihidbadgereqexpdt;
	}

	@Column(name = "NIHIDBADGEREQTYPE", length = 30)
	public String getNihidbadgereqtype() {
		return this.nihidbadgereqtype;
	}

	public void setNihidbadgereqtype(String nihidbadgereqtype) {
		this.nihidbadgereqtype = nihidbadgereqtype;
	}

	@Column(name = "NIHPOC", length = 30)
	public String getNihpoc() {
		return this.nihpoc;
	}

	public void setNihpoc(String nihpoc) {
		this.nihpoc = nihpoc;
	}

	@Column(name = "INACTIVE_DATE", length = 7)
	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	
	@OneToOne
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name="NIHSSOUSERNAME", insertable = false, updatable = false)
	public PersonRole getPersonRole() {
		return personRole;
	}
	
	public void setPersonRole(PersonRole personRole) {
		this.personRole = personRole;
	}
	
	/*@OneToOne
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name="NIHSSOUSERNAME", insertable = false, updatable = false)
	public UserRole getUserRole() {
		return userRole;
	}
	
	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}*/
	

	/**
	 * Gets the full name.
	 * 
	 * @return the full name
	 */
	@Transient
	public String getFullName() {

		final StringBuffer sb = new StringBuffer(40);

		if (StringUtils.isNotBlank(getPreferredName())) {
			sb.append(getPreferredName());
		} else {
			sb.append(getFirstName());
		}
		sb.append(" ");

		sb.append(getLastName());
		return WordUtils.capitalizeFully(sb.toString());
	}
	
	/**
	 * Gets the full name.
	 * 
	 * @return the full name
	 */
	@Transient
	public String getFullNameLF() {

		final StringBuffer sb = new StringBuffer(40);

		sb.append(getLastName());
		sb.append(", ");
		if (StringUtils.isNotBlank(getPreferredName())) {
			sb.append(getPreferredName());
		} else {
			sb.append(getFirstName());
		}

		return sb.toString();
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NedPerson))
			return false;
		NedPerson castOther = (NedPerson) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getNedId() == castOther.getNedId())
						|| (this.getNedId() != null && castOther.getNedId() != null
								&& this.getNedId().equals(castOther.getNedId())))
				&& ((this.getBuilding() == castOther.getBuilding())
						|| (this.getBuilding() != null && castOther.getBuilding() != null
								&& this.getBuilding().equals(castOther.getBuilding())))
				&& ((this.getC() == castOther.getC())
						|| (this.getC() != null && castOther.getC() != null && this.getC().equals(castOther.getC())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getFacsimiletelephone() == castOther.getFacsimiletelephone())
						|| (this.getFacsimiletelephone() != null && castOther.getFacsimiletelephone() != null
								&& this.getFacsimiletelephone().equals(castOther.getFacsimiletelephone())))
				&& ((this.getGenerationqualif() == castOther.getGenerationqualif())
						|| (this.getGenerationqualif() != null && castOther.getGenerationqualif() != null
								&& this.getGenerationqualif().equals(castOther.getGenerationqualif())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
						&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getInitials() == castOther.getInitials()) || (this.getInitials() != null
						&& castOther.getInitials() != null && this.getInitials().equals(castOther.getInitials())))
				&& ((this.getL() == castOther.getL())
						|| (this.getL() != null && castOther.getL() != null && this.getL().equals(castOther.getL())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null && castOther.getEmail() != null
						&& this.getEmail().equals(castOther.getEmail())))
				&& ((this.getManager() == castOther.getManager()) || (this.getManager() != null
						&& castOther.getManager() != null && this.getManager().equals(castOther.getManager())))
				&& ((this.getMiddlename() == castOther.getMiddlename())
						|| (this.getMiddlename() != null && castOther.getMiddlename() != null
								&& this.getMiddlename().equals(castOther.getMiddlename())))
				&& ((this.getMobiletelephonenum() == castOther.getMobiletelephonenum())
						|| (this.getMobiletelephonenum() != null && castOther.getMobiletelephonenum() != null
								&& this.getMobiletelephonenum().equals(castOther.getMobiletelephonenum())))
				&& ((this.getNihbadgetitle() == castOther.getNihbadgetitle())
						|| (this.getNihbadgetitle() != null && castOther.getNihbadgetitle() != null
								&& this.getNihbadgetitle().equals(castOther.getNihbadgetitle())))
				&& ((this.getNihcommongenqualif() == castOther.getNihcommongenqualif())
						|| (this.getNihcommongenqualif() != null && castOther.getNihcommongenqualif() != null
								&& this.getNihcommongenqualif().equals(castOther.getNihcommongenqualif())))
				&& ((this.getPreferredName() == castOther.getPreferredName())
						|| (this.getPreferredName() != null && castOther.getPreferredName() != null
								&& this.getPreferredName().equals(castOther.getPreferredName())))
				&& ((this.getNihcommonmiddlenam() == castOther.getNihcommonmiddlenam())
						|| (this.getNihcommonmiddlenam() != null && castOther.getNihcommonmiddlenam() != null
								&& this.getNihcommonmiddlenam().equals(castOther.getNihcommonmiddlenam())))
				&& ((this.getNihcommonsn() == castOther.getNihcommonsn())
						|| (this.getNihcommonsn() != null && castOther.getNihcommonsn() != null
								&& this.getNihcommonsn().equals(castOther.getNihcommonsn())))
				&& ((this.getNihcreatetimestamp() == castOther.getNihcreatetimestamp())
						|| (this.getNihcreatetimestamp() != null && castOther.getNihcreatetimestamp() != null
								&& this.getNihcreatetimestamp().equals(castOther.getNihcreatetimestamp())))
				&& ((this.getNihcreatorsname() == castOther.getNihcreatorsname())
						|| (this.getNihcreatorsname() != null && castOther.getNihcreatorsname() != null
								&& this.getNihcreatorsname().equals(castOther.getNihcreatorsname())))
				&& ((this.getNihdeliveryaddress() == castOther.getNihdeliveryaddress())
						|| (this.getNihdeliveryaddress() != null && castOther.getNihdeliveryaddress() != null
								&& this.getNihdeliveryaddress().equals(castOther.getNihdeliveryaddress())))
				&& ((this.getNihdirentryeffectivedate() == castOther.getNihdirentryeffectivedate())
						|| (this.getNihdirentryeffectivedate() != null
								&& castOther.getNihdirentryeffectivedate() != null
								&& this.getNihdirentryeffectivedate().equals(castOther.getNihdirentryeffectivedate())))
				&& ((this.getNihdirentryexpirationdate() == castOther.getNihdirentryexpirationdate())
						|| (this.getNihdirentryexpirationdate() != null
								&& castOther.getNihdirentryexpirationdate() != null
								&& this.getNihdirentryexpirationdate()
										.equals(castOther.getNihdirentryexpirationdate())))
				&& ((this.getNihdirentrynoprint() == castOther.getNihdirentrynoprint())
						|| (this.getNihdirentrynoprint() != null && castOther.getNihdirentrynoprint() != null
								&& this.getNihdirentrynoprint().equals(castOther.getNihdirentrynoprint())))
				&& ((this.getNihdirentryunlist() == castOther.getNihdirentryunlist())
						|| (this.getNihdirentryunlist() != null && castOther.getNihdirentryunlist() != null
								&& this.getNihdirentryunlist().equals(castOther.getNihdirentryunlist())))
				&& ((this.getNihhhsuniquemail() == castOther.getNihhhsuniquemail())
						|| (this.getNihhhsuniquemail() != null && castOther.getNihhhsuniquemail() != null
								&& this.getNihhhsuniquemail().equals(castOther.getNihhhsuniquemail())))
				&& ((this.getNihidbadgeexpdate() == castOther.getNihidbadgeexpdate())
						|| (this.getNihidbadgeexpdate() != null && castOther.getNihidbadgeexpdate() != null
								&& this.getNihidbadgeexpdate().equals(castOther.getNihidbadgeexpdate())))
				&& ((this.getNihidbadgeissuerea() == castOther.getNihidbadgeissuerea())
						|| (this.getNihidbadgeissuerea() != null && castOther.getNihidbadgeissuerea() != null
								&& this.getNihidbadgeissuerea().equals(castOther.getNihidbadgeissuerea())))
				&& ((this.getNihidbadgereqdate() == castOther.getNihidbadgereqdate())
						|| (this.getNihidbadgereqdate() != null && castOther.getNihidbadgereqdate() != null
								&& this.getNihidbadgereqdate().equals(castOther.getNihidbadgereqdate())))
				&& ((this.getNihipd() == castOther.getNihipd()) || (this.getNihipd() != null
						&& castOther.getNihipd() != null && this.getNihipd().equals(castOther.getNihipd())))
				&& ((this.getNihlibraryauth() == castOther.getNihlibraryauth())
						|| (this.getNihlibraryauth() != null && castOther.getNihlibraryauth() != null
								&& this.getNihlibraryauth().equals(castOther.getNihlibraryauth())))
				&& ((this.getNihmailstop() == castOther.getNihmailstop())
						|| (this.getNihmailstop() != null && castOther.getNihmailstop() != null
								&& this.getNihmailstop().equals(castOther.getNihmailstop())))
				&& ((this.getAdUserId() == castOther.getAdUserId())
						|| (this.getAdUserId() != null && castOther.getAdUserId() != null
								&& this.getAdUserId().equals(castOther.getAdUserId())))
				&& ((this.getNihmdslinktohelp() == castOther.getNihmdslinktohelp())
						|| (this.getNihmdslinktohelp() != null && castOther.getNihmdslinktohelp() != null
								&& this.getNihmdslinktohelp().equals(castOther.getNihmdslinktohelp())))
				&& ((this.getNihmdslinktoph() == castOther.getNihmdslinktoph())
						|| (this.getNihmdslinktoph() != null && castOther.getNihmdslinktoph() != null
								&& this.getNihmdslinktoph().equals(castOther.getNihmdslinktoph())))
				&& ((this.getNihmixcasecommonsn() == castOther.getNihmixcasecommonsn())
						|| (this.getNihmixcasecommonsn() != null && castOther.getNihmixcasecommonsn() != null
								&& this.getNihmixcasecommonsn().equals(castOther.getNihmixcasecommonsn())))
				&& ((this.getLastName() == castOther.getLastName())
						|| (this.getLastName() != null && castOther.getLastName() != null
								&& this.getLastName().equals(castOther.getLastName())))
				&& ((this.getNihmodifiersname() == castOther.getNihmodifiersname())
						|| (this.getNihmodifiersname() != null && castOther.getNihmodifiersname() != null
								&& this.getNihmodifiersname().equals(castOther.getNihmodifiersname())))
				&& ((this.getNihmodifytimestamp() == castOther.getNihmodifytimestamp())
						|| (this.getNihmodifytimestamp() != null && castOther.getNihmodifytimestamp() != null
								&& this.getNihmodifytimestamp().equals(castOther.getNihmodifytimestamp())))
				&& ((this.getNihorgacronym() == castOther.getNihorgacronym())
						|| (this.getNihorgacronym() != null && castOther.getNihorgacronym() != null
								&& this.getNihorgacronym().equals(castOther.getNihorgacronym())))
				&& ((this.getNihorgname() == castOther.getNihorgname())
						|| (this.getNihorgname() != null && castOther.getNihorgname() != null
								&& this.getNihorgname().equals(castOther.getNihorgname())))
				&& ((this.getOrgpath() == castOther.getOrgpath())
						|| (this.getOrgpath() != null && castOther.getOrgpath() != null
								&& this.getOrgpath().equals(castOther.getOrgpath())))
				&& ((this.getNihouacronym() == castOther.getNihouacronym())
						|| (this.getNihouacronym() != null && castOther.getNihouacronym() != null
								&& this.getNihouacronym().equals(castOther.getNihouacronym())))
				&& ((this.getNihouname() == castOther.getNihouname()) || (this.getNihouname() != null
						&& castOther.getNihouname() != null && this.getNihouname().equals(castOther.getNihouname())))
				&& ((this.getNihphysicaladdress() == castOther.getNihphysicaladdress())
						|| (this.getNihphysicaladdress() != null && castOther.getNihphysicaladdress() != null
								&& this.getNihphysicaladdress().equals(castOther.getNihphysicaladdress())))
				&& ((this.getNihphyspostalcode() == castOther.getNihphyspostalcode())
						|| (this.getNihphyspostalcode() != null && castOther.getNihphyspostalcode() != null
								&& this.getNihphyspostalcode().equals(castOther.getNihphyspostalcode())))
				&& ((this.getNihsac() == castOther.getNihsac()) || (this.getNihsac() != null
						&& castOther.getNihsac() != null && this.getNihsac().equals(castOther.getNihsac())))
				&& ((this.getNihsite() == castOther.getNihsite()) || (this.getNihsite() != null
						&& castOther.getNihsite() != null && this.getNihsite().equals(castOther.getNihsite())))
				&& ((this.getNihssodomain() == castOther.getNihssodomain())
						|| (this.getNihssodomain() != null && castOther.getNihssodomain() != null
								&& this.getNihssodomain().equals(castOther.getNihssodomain())))
				&& ((this.getNihssousername() == castOther.getNihssousername())
						|| (this.getNihssousername() != null && castOther.getNihssousername() != null
								&& this.getNihssousername().equals(castOther.getNihssousername())))
				&& ((this.getNihsuffixqualifier() == castOther.getNihsuffixqualifier())
						|| (this.getNihsuffixqualifier() != null && castOther.getNihsuffixqualifier() != null
								&& this.getNihsuffixqualifier().equals(castOther.getNihsuffixqualifier())))
				&& ((this.getNihsummerstatus() == castOther.getNihsummerstatus())
						|| (this.getNihsummerstatus() != null && castOther.getNihsummerstatus() != null
								&& this.getNihsummerstatus().equals(castOther.getNihsummerstatus())))
				&& ((this.getNihtty() == castOther.getNihtty()) || (this.getNihtty() != null
						&& castOther.getNihtty() != null && this.getNihtty().equals(castOther.getNihtty())))
				&& ((this.getNihuidquality() == castOther.getNihuidquality())
						|| (this.getNihuidquality() != null && castOther.getNihuidquality() != null
								&& this.getNihuidquality().equals(castOther.getNihuidquality())))
				&& ((this.getNihuidvalidationts() == castOther.getNihuidvalidationts())
						|| (this.getNihuidvalidationts() != null && castOther.getNihuidvalidationts() != null
								&& this.getNihuidvalidationts().equals(castOther.getNihuidvalidationts())))
				&& ((this.getNihuidvalidator() == castOther.getNihuidvalidator())
						|| (this.getNihuidvalidator() != null && castOther.getNihuidvalidator() != null
								&& this.getNihuidvalidator().equals(castOther.getNihuidvalidator())))
				&& ((this.getNihuniquemail() == castOther.getNihuniquemail())
						|| (this.getNihuniquemail() != null && castOther.getNihuniquemail() != null
								&& this.getNihuniquemail().equals(castOther.getNihuniquemail())))
				&& ((this.getOrgStatus() == castOther.getOrgStatus())
						|| (this.getOrgStatus() != null && castOther.getOrgStatus() != null
								&& this.getOrgStatus().equals(castOther.getOrgStatus())))
				&& ((this.getPagertelephonenum() == castOther.getPagertelephonenum())
						|| (this.getPagertelephonenum() != null && castOther.getPagertelephonenum() != null
								&& this.getPagertelephonenum().equals(castOther.getPagertelephonenum())))
				&& ((this.getPersonaltitle() == castOther.getPersonaltitle())
						|| (this.getPersonaltitle() != null && castOther.getPersonaltitle() != null
								&& this.getPersonaltitle().equals(castOther.getPersonaltitle())))
				&& ((this.getPostaladdress() == castOther.getPostaladdress())
						|| (this.getPostaladdress() != null && castOther.getPostaladdress() != null
								&& this.getPostaladdress().equals(castOther.getPostaladdress())))
				&& ((this.getPostalcode() == castOther.getPostalcode())
						|| (this.getPostalcode() != null && castOther.getPostalcode() != null
								&& this.getPostalcode().equals(castOther.getPostalcode())))
				&& ((this.getRoom() == castOther.getRoom())
						|| (this.getRoom() != null && castOther.getRoom() != null
								&& this.getRoom().equals(castOther.getRoom())))
				&& ((this.getSecretary() == castOther.getSecretary()) || (this.getSecretary() != null
						&& castOther.getSecretary() != null && this.getSecretary().equals(castOther.getSecretary())))
				&& ((this.getSt() == castOther.getSt()) || (this.getSt() != null && castOther.getSt() != null
						&& this.getSt().equals(castOther.getSt())))
				&& ((this.getStreet() == castOther.getStreet()) || (this.getStreet() != null
						&& castOther.getStreet() != null && this.getStreet().equals(castOther.getStreet())))
				&& ((this.getPhone() == castOther.getPhone())
						|| (this.getPhone() != null && castOther.getPhone() != null
								&& this.getPhone().equals(castOther.getPhone())))
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getNihprimarysmtp() == castOther.getNihprimarysmtp())
						|| (this.getNihprimarysmtp() != null && castOther.getNihprimarysmtp() != null
								&& this.getNihprimarysmtp().equals(castOther.getNihprimarysmtp())))
				&& ((this.getNihdupuid() == castOther.getNihdupuid()) || (this.getNihdupuid() != null
						&& castOther.getNihdupuid() != null && this.getNihdupuid().equals(castOther.getNihdupuid())))
				&& ((this.getNihidbadgeless6mos() == castOther.getNihidbadgeless6mos())
						|| (this.getNihidbadgeless6mos() != null && castOther.getNihidbadgeless6mos() != null
								&& this.getNihidbadgeless6mos().equals(castOther.getNihidbadgeless6mos())))
				&& ((this.getNihnomiddlename() == castOther.getNihnomiddlename())
						|| (this.getNihnomiddlename() != null && castOther.getNihnomiddlename() != null
								&& this.getNihnomiddlename().equals(castOther.getNihnomiddlename())))
				&& ((this.getNihidbadgereqexpdt() == castOther.getNihidbadgereqexpdt())
						|| (this.getNihidbadgereqexpdt() != null && castOther.getNihidbadgereqexpdt() != null
								&& this.getNihidbadgereqexpdt().equals(castOther.getNihidbadgereqexpdt())))
				&& ((this.getNihidbadgereqtype() == castOther.getNihidbadgereqtype())
						|| (this.getNihidbadgereqtype() != null && castOther.getNihidbadgereqtype() != null
								&& this.getNihidbadgereqtype().equals(castOther.getNihidbadgereqtype())))
				&& ((this.getNihpoc() == castOther.getNihpoc()) || (this.getNihpoc() != null
						&& castOther.getNihpoc() != null && this.getNihpoc().equals(castOther.getNihpoc())))
				&& ((this.getInactiveDate() == castOther.getInactiveDate())
						|| (this.getInactiveDate() != null && castOther.getInactiveDate() != null
								&& this.getInactiveDate().equals(castOther.getInactiveDate())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate())
						|| (this.getCreatedDate() != null && castOther.getCreatedDate() != null
								&& this.getCreatedDate().equals(castOther.getCreatedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getNedId() == null ? 0 : this.getNedId().hashCode());
		result = 37 * result + (getBuilding() == null ? 0 : this.getBuilding().hashCode());
		result = 37 * result + (getC() == null ? 0 : this.getC().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getFacsimiletelephone() == null ? 0 : this.getFacsimiletelephone().hashCode());
		result = 37 * result + (getGenerationqualif() == null ? 0 : this.getGenerationqualif().hashCode());
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getInitials() == null ? 0 : this.getInitials().hashCode());
		result = 37 * result + (getL() == null ? 0 : this.getL().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getManager() == null ? 0 : this.getManager().hashCode());
		result = 37 * result + (getMiddlename() == null ? 0 : this.getMiddlename().hashCode());
		result = 37 * result + (getMobiletelephonenum() == null ? 0 : this.getMobiletelephonenum().hashCode());
		result = 37 * result + (getNihbadgetitle() == null ? 0 : this.getNihbadgetitle().hashCode());
		result = 37 * result + (getNihcommongenqualif() == null ? 0 : this.getNihcommongenqualif().hashCode());
		result = 37 * result + (getPreferredName() == null ? 0 : this.getPreferredName().hashCode());
		result = 37 * result + (getNihcommonmiddlenam() == null ? 0 : this.getNihcommonmiddlenam().hashCode());
		result = 37 * result + (getNihcommonsn() == null ? 0 : this.getNihcommonsn().hashCode());
		result = 37 * result + (getNihcreatetimestamp() == null ? 0 : this.getNihcreatetimestamp().hashCode());
		result = 37 * result + (getNihcreatorsname() == null ? 0 : this.getNihcreatorsname().hashCode());
		result = 37 * result + (getNihdeliveryaddress() == null ? 0 : this.getNihdeliveryaddress().hashCode());
		result = 37 * result
				+ (getNihdirentryeffectivedate() == null ? 0 : this.getNihdirentryeffectivedate().hashCode());
		result = 37 * result
				+ (getNihdirentryexpirationdate() == null ? 0 : this.getNihdirentryexpirationdate().hashCode());
		result = 37 * result + (getNihdirentrynoprint() == null ? 0 : this.getNihdirentrynoprint().hashCode());
		result = 37 * result + (getNihdirentryunlist() == null ? 0 : this.getNihdirentryunlist().hashCode());
		result = 37 * result + (getNihhhsuniquemail() == null ? 0 : this.getNihhhsuniquemail().hashCode());
		result = 37 * result + (getNihidbadgeexpdate() == null ? 0 : this.getNihidbadgeexpdate().hashCode());
		result = 37 * result + (getNihidbadgeissuerea() == null ? 0 : this.getNihidbadgeissuerea().hashCode());
		result = 37 * result + (getNihidbadgereqdate() == null ? 0 : this.getNihidbadgereqdate().hashCode());
		result = 37 * result + (getNihipd() == null ? 0 : this.getNihipd().hashCode());
		result = 37 * result + (getNihlibraryauth() == null ? 0 : this.getNihlibraryauth().hashCode());
		result = 37 * result + (getNihmailstop() == null ? 0 : this.getNihmailstop().hashCode());
		result = 37 * result + (getAdUserId() == null ? 0 : this.getAdUserId().hashCode());
		result = 37 * result + (getNihmdslinktohelp() == null ? 0 : this.getNihmdslinktohelp().hashCode());
		result = 37 * result + (getNihmdslinktoph() == null ? 0 : this.getNihmdslinktoph().hashCode());
		result = 37 * result + (getNihmixcasecommonsn() == null ? 0 : this.getNihmixcasecommonsn().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getNihmodifiersname() == null ? 0 : this.getNihmodifiersname().hashCode());
		result = 37 * result + (getNihmodifytimestamp() == null ? 0 : this.getNihmodifytimestamp().hashCode());
		result = 37 * result + (getNihorgacronym() == null ? 0 : this.getNihorgacronym().hashCode());
		result = 37 * result + (getNihorgname() == null ? 0 : this.getNihorgname().hashCode());
		result = 37 * result + (getOrgpath() == null ? 0 : this.getOrgpath().hashCode());
		result = 37 * result + (getNihouacronym() == null ? 0 : this.getNihouacronym().hashCode());
		result = 37 * result + (getNihouname() == null ? 0 : this.getNihouname().hashCode());
		result = 37 * result + (getNihphysicaladdress() == null ? 0 : this.getNihphysicaladdress().hashCode());
		result = 37 * result + (getNihphyspostalcode() == null ? 0 : this.getNihphyspostalcode().hashCode());
		result = 37 * result + (getNihsac() == null ? 0 : this.getNihsac().hashCode());
		result = 37 * result + (getNihsite() == null ? 0 : this.getNihsite().hashCode());
		result = 37 * result + (getNihssodomain() == null ? 0 : this.getNihssodomain().hashCode());
		result = 37 * result + (getNihssousername() == null ? 0 : this.getNihssousername().hashCode());
		result = 37 * result + (getNihsuffixqualifier() == null ? 0 : this.getNihsuffixqualifier().hashCode());
		result = 37 * result + (getNihsummerstatus() == null ? 0 : this.getNihsummerstatus().hashCode());
		result = 37 * result + (getNihtty() == null ? 0 : this.getNihtty().hashCode());
		result = 37 * result + (getNihuidquality() == null ? 0 : this.getNihuidquality().hashCode());
		result = 37 * result + (getNihuidvalidationts() == null ? 0 : this.getNihuidvalidationts().hashCode());
		result = 37 * result + (getNihuidvalidator() == null ? 0 : this.getNihuidvalidator().hashCode());
		result = 37 * result + (getNihuniquemail() == null ? 0 : this.getNihuniquemail().hashCode());
		result = 37 * result + (getOrgStatus() == null ? 0 : this.getOrgStatus().hashCode());
		result = 37 * result + (getPagertelephonenum() == null ? 0 : this.getPagertelephonenum().hashCode());
		result = 37 * result + (getPersonaltitle() == null ? 0 : this.getPersonaltitle().hashCode());
		result = 37 * result + (getPostaladdress() == null ? 0 : this.getPostaladdress().hashCode());
		result = 37 * result + (getPostalcode() == null ? 0 : this.getPostalcode().hashCode());
		result = 37 * result + (getRoom() == null ? 0 : this.getRoom().hashCode());
		result = 37 * result + (getSecretary() == null ? 0 : this.getSecretary().hashCode());
		result = 37 * result + (getSt() == null ? 0 : this.getSt().hashCode());
		result = 37 * result + (getStreet() == null ? 0 : this.getStreet().hashCode());
		result = 37 * result + (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getNihprimarysmtp() == null ? 0 : this.getNihprimarysmtp().hashCode());
		result = 37 * result + (getNihdupuid() == null ? 0 : this.getNihdupuid().hashCode());
		result = 37 * result + (getNihidbadgeless6mos() == null ? 0 : this.getNihidbadgeless6mos().hashCode());
		result = 37 * result + (getNihnomiddlename() == null ? 0 : this.getNihnomiddlename().hashCode());
		result = 37 * result + (getNihidbadgereqexpdt() == null ? 0 : this.getNihidbadgereqexpdt().hashCode());
		result = 37 * result + (getNihidbadgereqtype() == null ? 0 : this.getNihidbadgereqtype().hashCode());
		result = 37 * result + (getNihpoc() == null ? 0 : this.getNihpoc().hashCode());
		result = 37 * result + (getInactiveDate() == null ? 0 : this.getInactiveDate().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		return result;
	}

}
