package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Jun 21, 2016 11:01:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocsVw generated by hbm2java
 */
@Entity
@Table(name = "DOCS_VW")
public class Organization implements java.io.Serializable {

	private String nihorgpath;
	private String nihsac;
	private String nihouacronym;
	private String nihouname;

	public Organization() {
	}

	public Organization(String nihsac) {
		this.nihsac = nihsac;
	}

	public Organization(String nihorgpath, String nihsac, String nihouacronym, String nihouname) {
		this.nihorgpath = nihorgpath;
		this.nihsac = nihsac;
		this.nihouacronym = nihouacronym;
		this.nihouname = nihouname;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof Organization)) {
			return false;
		}
		Organization castOther = (Organization) other;

		return (getNihorgpath() == castOther.getNihorgpath() || getNihorgpath() != null
				&& castOther.getNihorgpath() != null && getNihorgpath().equals(castOther.getNihorgpath()))
				&& (getNihsac() == castOther.getNihsac() || getNihsac() != null && castOther.getNihsac() != null
						&& getNihsac().equals(castOther.getNihsac()));
	}

	@Id
	@Column(name = "NIHORGPATH", length = 1004)
	public String getNihorgpath() {
		return nihorgpath;
	}

	@Column(name = "NIHSAC", nullable = false, length = 20)
	public String getNihsac() {
		return nihsac;
	}

	@Column(name = "NIHOUACRONYM", length = 64)
	public String getNihouacronym() {
		return nihouacronym;
	}

	@Column(name = "NIHOUNAME", nullable = false, length = 80)
	public String getNihouname() {
		return nihouname;
	}
	
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNihorgpath() == null ? 0 : getNihorgpath().hashCode());
		result = 37 * result + (getNihsac() == null ? 0 : getNihsac().hashCode());
		result = 37 * result + (getNihouacronym() == null ? 0 : getNihouacronym().hashCode());
		result = 37 * result + (getNihouname() == null ? 0 : getNihouname().hashCode());
		return result;
	}

	public void setNihorgpath(String nihorgpath) {
		this.nihorgpath = nihorgpath;
	}

	public void setNihsac(String nihsac) {
		this.nihsac = nihsac;
	}
	
	public void setNihouacronym(String nihouacronym) {
		this.nihouacronym = nihouacronym;
	}

	public void setNihouname(String nihouname) {
		this.nihouname = nihouname;
	}

}
