package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 4, 2016 12:46:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlanQuestionsAnswersT generated by hbm2java
 */
@Entity
@Table(name = "PLAN_QUESTIONS_ANSWERS_T")
public class PlanQuestionsAnswersT implements java.io.Serializable {

	private Long id;
	private Long projectId;
	private Long questionId;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;
	private PlanQuestionsT planQuestionsT;
	private ProjectsT projectsT;
	
	public PlanQuestionsAnswersT() {
	}

	public PlanQuestionsAnswersT(Long id, Long projectId, Long questionId, Date createdDate,
			String createdBy) {
		this.id = id;
		this.projectId = projectId;
		this.questionId = questionId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public PlanQuestionsAnswersT(Long id, Long projectId, Long questionId, Date createdDate,
			String createdBy, Date lastChangedDate, String lastChangedBy, 
			PlanQuestionsT planQuestionsT, ProjectsT projectsT) {
		this.id = id;
		this.projectId = projectId;
		this.questionId = questionId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
		this.planQuestionsT = planQuestionsT;
		this.projectsT = projectsT;
	}

	@Id
	
	@Column(name = "ID", nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PROJECT_ID", nullable = false, precision = 10, scale = 0)
	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	@Column(name = "QUESTION_ID", nullable = false, precision = 10, scale = 0)
	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID", nullable = false, insertable = false, updatable = false)
	public PlanQuestionsT getPlanQuestionsT() {
		return this.planQuestionsT;
	}

	public void setPlanQuestionsT(PlanQuestionsT planQuestionsT) {
		this.planQuestionsT = planQuestionsT;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false, insertable = false, updatable = false)
	public ProjectsT getProjectsT() {
		return this.projectsT;
	}

	public void setProjectsT(ProjectsT projectsT) {
		this.projectsT = projectsT;
	}

}
