package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 28, 2016 10:25:57 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * PlanQuestionsAnswer generated by hbm2java
 */
@Entity
@Table(name = "PLAN_QUESTIONS_ANSWERS_T")
public class PlanQuestionsAnswer implements java.io.Serializable {

	private Long id;
	private Long questionId;
	private String displayText;
	private Long displayOrderNum;
	private Boolean activeFlag;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;
	private Set<PlanAnswerSelection> planAnswerSelections = new HashSet<PlanAnswerSelection>(0);

	public PlanQuestionsAnswer() {
	}

	public PlanQuestionsAnswer(Long id, String displayText, Boolean activeFlag, Date createdDate,
			String createdBy) {
		this.id = id;
		this.displayText = displayText;
		this.activeFlag = activeFlag;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public PlanQuestionsAnswer(Long id, Long questionId, String displayText, Long displayOrderNum,
			Boolean activeFlag, Date createdDate, String createdBy, Date lastChangedDate, String lastChangedBy,
			Set<PlanAnswerSelection> planAnswerSelections) {
		this.id = id;
		this.questionId = questionId;
		this.displayText = displayText;
		this.displayOrderNum = displayOrderNum;
		this.activeFlag = activeFlag;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
		this.planAnswerSelections = planAnswerSelections;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "QUESTION_ID", precision = 10, scale = 0)
	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	@Column(name = "DISPLAY_TEXT", nullable = false, length = 800)
	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	@Column(name = "DISPLAY_ORDER_NUM", precision = 10, scale = 0)
	public Long getDisplayOrderNum() {
		return this.displayOrderNum;
	}

	public void setDisplayOrderNum(Long displayOrderNum) {
		this.displayOrderNum = displayOrderNum;
	}

	@Type(type="yes_no")
	@Column(name = "ACTIVE_FLAG", nullable = false, length = 4)
	public Boolean getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planQuestionsAnswer")
	public Set<PlanAnswerSelection> getPlanAnswerSelections() {
		return this.planAnswerSelections;
	}

	public void setPlanAnswerSelections(Set<PlanAnswerSelection> planAnswerSelections) {
		this.planAnswerSelections = planAnswerSelections;
	}

}
