package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 28, 2016 10:25:57 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanAnswerSelection generated by hbm2java
 */
@Entity
@Table(name = "PLAN_ANSWER_SELECTIONS_T")
public class PlanAnswerSelection implements java.io.Serializable {

	private Long id;
	private PlanQuestionsAnswer planQuestionsAnswer;
	private Project project;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;

	public PlanAnswerSelection() {
	}

	public PlanAnswerSelection(Long id, PlanQuestionsAnswer planQuestionsAnswer, Project project,
			Date createdDate, String createdBy) {
		this.id = id;
		this.planQuestionsAnswer = planQuestionsAnswer;
		this.project = project;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public PlanAnswerSelection(Long id, PlanQuestionsAnswer planQuestionsAnswer, Project project,
			Date createdDate, String createdBy, Date lastChangedDate, String lastChangedBy) {
		this.id = id;
		this.planQuestionsAnswer = planQuestionsAnswer;
		this.project = project;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ANSWER_ID", nullable = false)
	public PlanQuestionsAnswer getPlanQuestionsAnswer() {
		return this.planQuestionsAnswer;
	}

	public void setPlanQuestionsAnswer(PlanQuestionsAnswer planQuestionsAnswer) {
		this.planQuestionsAnswer = planQuestionsAnswer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

}
