package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 4, 2016 12:46:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanQuestionsT generated by hbm2java
 */
@Entity
@Table(name = "PLAN_QUESTIONS_T")
public class PlanQuestionsT implements java.io.Serializable {

	private Integer id;
	private Integer parentQuestionId;
	private String displayText;
	private Integer displayOrderNum;
	private String activeFlag;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;
	private Set<PlanQuestionsAnswersT> planQuestionsAnswersTs = new HashSet(0);

	public PlanQuestionsT() {
	}

	public PlanQuestionsT(Integer id, String displayText, String activeFlag, Date createdDate, String createdBy) {
		this.id = id;
		this.displayText = displayText;
		this.activeFlag = activeFlag;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public PlanQuestionsT(Integer id, Integer parentQuestionId, String displayText, Integer displayOrderNum,
			String activeFlag, Date createdDate, String createdBy, Date lastChangedDate, String lastChangedBy,
			Set planQuestionsAnswersTs) {
		this.id = id;
		this.parentQuestionId = parentQuestionId;
		this.displayText = displayText;
		this.displayOrderNum = displayOrderNum;
		this.activeFlag = activeFlag;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
		this.planQuestionsAnswersTs = planQuestionsAnswersTs;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PARENT_QUESTION_ID", precision = 10, scale = 0)
	public Integer getParentQuestionId() {
		return this.parentQuestionId;
	}

	public void setParentQuestionId(Integer parentQuestionId) {
		this.parentQuestionId = parentQuestionId;
	}

	@Column(name = "DISPLAY_TEXT", nullable = false, length = 800)
	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	@Column(name = "DISPLAY_ORDER_NUM", precision = 10, scale = 0)
	public Integer getDisplayOrderNum() {
		return this.displayOrderNum;
	}

	public void setDisplayOrderNum(Integer displayOrderNum) {
		this.displayOrderNum = displayOrderNum;
	}

	@Column(name = "ACTIVE_FLAG", nullable = false, length = 4)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planQuestionsT")
	public Set<PlanQuestionsAnswersT> getPlanQuestionsAnswersTs() {
		return this.planQuestionsAnswersTs;
	}

	public void setPlanQuestionsAnswersTs(Set<PlanQuestionsAnswersT> planQuestionsAnswersTs) {
		this.planQuestionsAnswersTs = planQuestionsAnswersTs;
	}

}
