package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 4, 2016 12:46:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectsT generated by hbm2java
 */
@Entity
@Table(name = "PROJECTS_T")
public class ProjectsT implements java.io.Serializable {

	private Long id;
	private String projectIdentifierNum;
	private String projectTitle;
	private String docAbbreviation;
	private String programBranch;
	private String nihFundedFlag;
	private String applicationNum;
	private String piFullName;
	private String pocFullName;
	private String institutionName;
	private String piEmailAddress;
	private String pdFullName;
	private Date projectStartDate;
	private Date projectEndDate;
	private Date sciRevApprovalDate;
	private String subStudyFlag;
	private String parentAccessionNum;
	private String comments;
	private String bsiReviewedFlag;
	private Long versionNum;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;
	private Set<StatusHistoryT> statusHistoryTs = new HashSet(0);
	private Set<DocumentsT> documentsTs = new HashSet(0);
	private Set<PlanQuestionsAnswersT> planQuestionsAnswersTs = new HashSet(0);
	private Set<RepositoryStatusesT> repositoryStatusesTs = new HashSet(0);
	private Set<InstitutionalCertificationsT> institutionalCertificationsTs = new HashSet(0);

	public ProjectsT() {
	}

	public ProjectsT(Long id, String projectIdentifierNum, String nihFundedFlag, Long versionNum,
			Date createdDate, String createdBy) {
		this.id = id;
		this.projectIdentifierNum = projectIdentifierNum;
		this.nihFundedFlag = nihFundedFlag;
		this.versionNum = versionNum;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	@Override
	public String toString() {
		return "ProjectsT [id=" + id + ", projectIdentifierNum=" + projectIdentifierNum + ", projectTitle="
				+ projectTitle + ", docAbbreviation=" + docAbbreviation + ", programBranch=" + programBranch
				+ ", nihFundedFlag=" + nihFundedFlag + ", applicationNum=" + applicationNum + ", piFullName="
				+ piFullName + ", pocFullName=" + pocFullName + ", institutionName=" + institutionName
				+ ", piEmailAddress=" + piEmailAddress + ", pdFullName=" + pdFullName + ", projectStartDate="
				+ projectStartDate + ", projectEndDate=" + projectEndDate + ", sciRevApprovalDate="
				+ sciRevApprovalDate + ", subStudyFlag=" + subStudyFlag + ", parentAccessionNum=" + parentAccessionNum
				+ ", comments=" + comments + ", bsiReviewedFlag=" + bsiReviewedFlag + ", versionNum=" + versionNum
				+ ", createdDate=" + createdDate + ", createdBy=" + createdBy + ", lastChangedDate=" + lastChangedDate
				+ ", lastChangedBy=" + lastChangedBy + ", statusHistoryTs=" + statusHistoryTs + ", documentsTs="
				+ documentsTs + ", planQuestionsAnswersTs=" + planQuestionsAnswersTs + ", repositoryStatusesTs="
				+ repositoryStatusesTs + ", institutionalCertificationsTs=" + institutionalCertificationsTs + "]";
	}

	public ProjectsT(Long id, String projectIdentifierNum, String projectTitle, String docAbbreviation,
			String programBranch, String nihFundedFlag, String applicationNum, String piFullName, String pocFullName,
			String institutionName, String piEmailAddress, String pdFullName, Date projectStartDate,
			Date projectEndDate, Date sciRevApprovalDate, String subStudyFlag, String parentAccessionNum,
			String comments, String bsiReviewedFlag, Long versionNum, Date createdDate, String createdBy,
			Date lastChangedDate, String lastChangedBy, Set statusHistoryTs, Set documentsTs,
			Set planQuestionsAnswersTs, Set repositoryStatusesTs, Set institutionalCertificationsTs) {
		this.id = id;
		this.projectIdentifierNum = projectIdentifierNum;
		this.projectTitle = projectTitle;
		this.docAbbreviation = docAbbreviation;
		this.programBranch = programBranch;
		this.nihFundedFlag = nihFundedFlag;
		this.applicationNum = applicationNum;
		this.piFullName = piFullName;
		this.pocFullName = pocFullName;
		this.institutionName = institutionName;
		this.piEmailAddress = piEmailAddress;
		this.pdFullName = pdFullName;
		this.projectStartDate = projectStartDate;
		this.projectEndDate = projectEndDate;
		this.sciRevApprovalDate = sciRevApprovalDate;
		this.subStudyFlag = subStudyFlag;
		this.parentAccessionNum = parentAccessionNum;
		this.comments = comments;
		this.bsiReviewedFlag = bsiReviewedFlag;
		this.versionNum = versionNum;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
		this.statusHistoryTs = statusHistoryTs;
		this.documentsTs = documentsTs;
		this.planQuestionsAnswersTs = planQuestionsAnswersTs;
		this.repositoryStatusesTs = repositoryStatusesTs;
		this.institutionalCertificationsTs = institutionalCertificationsTs;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PROJECT_IDENTIFIER_NUM", nullable = false, length = 120)
	public String getProjectIdentifierNum() {
		return this.projectIdentifierNum;
	}

	public void setProjectIdentifierNum(String projectIdentifierNum) {
		this.projectIdentifierNum = projectIdentifierNum;
	}

	@Column(name = "PROJECT_TITLE", length = 400)
	public String getProjectTitle() {
		return this.projectTitle;
	}

	public void setProjectTitle(String projectTitle) {
		this.projectTitle = projectTitle;
	}

	@Column(name = "DOC_ABBREVIATION", length = 120)
	public String getDocAbbreviation() {
		return this.docAbbreviation;
	}

	public void setDocAbbreviation(String docAbbreviation) {
		this.docAbbreviation = docAbbreviation;
	}

	@Column(name = "PROGRAM_BRANCH", length = 120)
	public String getProgramBranch() {
		return this.programBranch;
	}

	public void setProgramBranch(String programBranch) {
		this.programBranch = programBranch;
	}

	@Column(name = "NIH_FUNDED_FLAG", nullable = false, length = 4)
	public String getNihFundedFlag() {
		return this.nihFundedFlag;
	}

	public void setNihFundedFlag(String nihFundedFlag) {
		this.nihFundedFlag = nihFundedFlag;
	}

	@Column(name = "APPLICATION_NUM", length = 120)
	public String getApplicationNum() {
		return this.applicationNum;
	}

	public void setApplicationNum(String applicationNum) {
		this.applicationNum = applicationNum;
	}

	@Column(name = "PI_FULL_NAME", length = 400)
	public String getPiFullName() {
		return this.piFullName;
	}

	public void setPiFullName(String piFullName) {
		this.piFullName = piFullName;
	}

	@Column(name = "POC_FULL_NAME", length = 400)
	public String getPocFullName() {
		return this.pocFullName;
	}

	public void setPocFullName(String pocFullName) {
		this.pocFullName = pocFullName;
	}

	@Column(name = "INSTITUTION_NAME", length = 480)
	public String getInstitutionName() {
		return this.institutionName;
	}

	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}

	@Column(name = "PI_EMAIL_ADDRESS", length = 320)
	public String getPiEmailAddress() {
		return this.piEmailAddress;
	}

	public void setPiEmailAddress(String piEmailAddress) {
		this.piEmailAddress = piEmailAddress;
	}

	@Column(name = "PD_FULL_NAME", length = 400)
	public String getPdFullName() {
		return this.pdFullName;
	}

	public void setPdFullName(String pdFullName) {
		this.pdFullName = pdFullName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROJECT_START_DATE", length = 7)
	public Date getProjectStartDate() {
		return this.projectStartDate;
	}

	public void setProjectStartDate(Date projectStartDate) {
		this.projectStartDate = projectStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROJECT_END_DATE", length = 7)
	public Date getProjectEndDate() {
		return this.projectEndDate;
	}

	public void setProjectEndDate(Date projectEndDate) {
		this.projectEndDate = projectEndDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SCI_REV_APPROVAL_DATE", length = 7)
	public Date getSciRevApprovalDate() {
		return this.sciRevApprovalDate;
	}

	public void setSciRevApprovalDate(Date sciRevApprovalDate) {
		this.sciRevApprovalDate = sciRevApprovalDate;
	}

	@Column(name = "SUB_STUDY_FLAG", length = 4)
	public String getSubStudyFlag() {
		return this.subStudyFlag;
	}

	public void setSubStudyFlag(String subStudyFlag) {
		this.subStudyFlag = subStudyFlag;
	}

	@Column(name = "PARENT_ACCESSION_NUM", length = 120)
	public String getParentAccessionNum() {
		return this.parentAccessionNum;
	}

	public void setParentAccessionNum(String parentAccessionNum) {
		this.parentAccessionNum = parentAccessionNum;
	}

	@Column(name = "COMMENTS", length = 4000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "BSI_REVIEWED_FLAG", length = 4)
	public String getBsiReviewedFlag() {
		return this.bsiReviewedFlag;
	}

	public void setBsiReviewedFlag(String bsiReviewedFlag) {
		this.bsiReviewedFlag = bsiReviewedFlag;
	}

	@Column(name = "VERSION_NUM", nullable = false, precision = 10, scale = 0)
	public Long getVersionNum() {
		return this.versionNum;
	}

	public void setVersionNum(Long versionNum) {
		this.versionNum = versionNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectsT")
	public Set<StatusHistoryT> getStatusHistoryTs() {
		return this.statusHistoryTs;
	}

	public void setStatusHistoryTs(Set<StatusHistoryT> statusHistoryTs) {
		this.statusHistoryTs = statusHistoryTs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectsT")
	public Set<DocumentsT> getDocumentsTs() {
		return this.documentsTs;
	}

	public void setDocumentsTs(Set<DocumentsT> documentsTs) {
		this.documentsTs = documentsTs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectsT")
	public Set<PlanQuestionsAnswersT> getPlanQuestionsAnswersTs() {
		return this.planQuestionsAnswersTs;
	}

	public void setPlanQuestionsAnswersTs(Set<PlanQuestionsAnswersT> planQuestionsAnswersTs) {
		this.planQuestionsAnswersTs = planQuestionsAnswersTs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectsT")
	public Set<RepositoryStatusesT> getRepositoryStatusesTs() {
		return this.repositoryStatusesTs;
	}

	public void setRepositoryStatusesTs(Set<RepositoryStatusesT> repositoryStatusesTs) {
		this.repositoryStatusesTs = repositoryStatusesTs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectsT")
	public Set<InstitutionalCertificationsT> getInstitutionalCertificationsTs() {
		return this.institutionalCertificationsTs;
	}

	public void setInstitutionalCertificationsTs(Set<InstitutionalCertificationsT> institutionalCertificationsTs) {
		this.institutionalCertificationsTs = institutionalCertificationsTs;
	}

}
