package gov.nih.nci.cbiit.scimgmt.gds.domain;

// Generated Feb 26, 2016 2:29:04 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "PROPERTIES_T", schema = "GDS")
public class Property implements java.io.Serializable {

	private String propKey;
	private String propValue;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;

	public Property() {
	}

	public Property(String propKey, String propValue, Date createdDate,
			String createdBy) {
		this.propKey = propKey;
		this.propValue = propValue;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public Property(String propKey, String propValue, Date createdDate,
			String createdBy, Date lastChangedDate, String lastChangedBy) {
		this.propKey = propKey;
		this.propValue = propValue;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
	}

	@Id
	@Column(name = "PROP_KEY", unique = true, nullable = false, length = 120)
	public String getPropKey() {
		return this.propKey;
	}

	public void setPropKey(String propKey) {
		this.propKey = propKey;
	}

	@Column(name = "PROP_VALUE", nullable = false, length = 800)
	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

}
