package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 4, 2016 12:46:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StatusHistoryT generated by hbm2java
 */
@Entity
@Table(name = "STATUS_HISTORY_T")
public class StatusHistoryT implements java.io.Serializable {

	private Long id;
	private LookupT lookupT;
	private ProjectsT projectsT;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;

	public StatusHistoryT() {
	}

	public StatusHistoryT(Long id, LookupT lookupT, ProjectsT projectsT, Date createdDate) {
		this.id = id;
		this.lookupT = lookupT;
		this.projectsT = projectsT;
		this.createdDate = createdDate;
	}

	public StatusHistoryT(Long id, LookupT lookupT, ProjectsT projectsT, Date createdDate, String createdBy,
			Date lastChangedDate, String lastChangedBy) {
		this.id = id;
		this.lookupT = lookupT;
		this.projectsT = projectsT;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS_ID", nullable = false)
	public LookupT getLookupT() {
		return this.lookupT;
	}

	public void setLookupT(LookupT lookupT) {
		this.lookupT = lookupT;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false)
	public ProjectsT getProjectsT() {
		return this.projectsT;
	}

	public void setProjectsT(ProjectsT projectsT) {
		this.projectsT = projectsT;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

}
