package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 28, 2016 10:25:57 AM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudiesDulSet generated by hbm2java
 */
@Entity
@Table(name = "STUDIES_DUL_SET_T")
public class StudiesDulSet implements java.io.Serializable {

	private Long id;
	private Study study;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;
	private List<DulChecklistSelection> dulChecklistSelections = new ArrayList<DulChecklistSelection>();

	public StudiesDulSet() {
	}

	public StudiesDulSet(Long id, Study study, Date createdDate, String createdBy) {
		this.id = id;
		this.study = study;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public StudiesDulSet(Long id, Study study, Date createdDate, String createdBy, Date lastChangedDate,
			String lastChangedBy, List<DulChecklistSelection> dulChecklistSelections) {
		this.id = id;
		this.study = study;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
		this.dulChecklistSelections = dulChecklistSelections;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUDY_ID", nullable = false)
	public Study getStudy() {
		return this.study;
	}

	public void setStudy(Study study) {
		this.study = study;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studiesDulSet")
	public List<DulChecklistSelection> getDulChecklistSelections() {
		return this.dulChecklistSelections;
	}

	public void setDulChecklistSelections(List<DulChecklistSelection> dulChecklistSelections) {
		this.dulChecklistSelections = dulChecklistSelections;
	}
	
	public void addDulChecklistSelection(DulChecklistSelection dulChecklistSelection) {
		this.dulChecklistSelections.add(dulChecklistSelection);
	}

}
