package gov.nih.nci.cbiit.scimgmt.gds.domain;
// Generated Mar 4, 2016 12:46:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudiesT generated by hbm2java
 */
@Entity
@Table(name = "STUDIES_T")
public class StudiesT implements java.io.Serializable {

	private Long id;
	private InstitutionalCertificationsT institutionalCertificationsT;
	private String studyName;
	private String institutionName;
	private String dulVerificationCode;
	private Date createdDate;
	private String createdBy;
	private Date lastChangedDate;
	private String lastChangedBy;
	private Set<DulChecklistSelectionsT> dulChecklistSelectionsTs = new HashSet(0);

	public StudiesT() {
	}

	public StudiesT(Long id, InstitutionalCertificationsT institutionalCertificationsT, String studyName,
			Date createdDate, String createdBy) {
		this.id = id;
		this.institutionalCertificationsT = institutionalCertificationsT;
		this.studyName = studyName;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public StudiesT(Long id, InstitutionalCertificationsT institutionalCertificationsT, String studyName,
			String institutionName, String dulVerificationCode, Date createdDate, String createdBy,
			Date lastChangedDate, String lastChangedBy, Set dulChecklistSelectionsTs) {
		this.id = id;
		this.institutionalCertificationsT = institutionalCertificationsT;
		this.studyName = studyName;
		this.institutionName = institutionName;
		this.dulVerificationCode = dulVerificationCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.lastChangedDate = lastChangedDate;
		this.lastChangedBy = lastChangedBy;
		this.dulChecklistSelectionsTs = dulChecklistSelectionsTs;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CERTIFICATION_ID", nullable = false)
	public InstitutionalCertificationsT getInstitutionalCertificationsT() {
		return this.institutionalCertificationsT;
	}

	public void setInstitutionalCertificationsT(InstitutionalCertificationsT institutionalCertificationsT) {
		this.institutionalCertificationsT = institutionalCertificationsT;
	}

	@Column(name = "STUDY_NAME", nullable = false, length = 400)
	public String getStudyName() {
		return this.studyName;
	}

	public void setStudyName(String studyName) {
		this.studyName = studyName;
	}

	@Column(name = "INSTITUTION_NAME", length = 480)
	public String getInstitutionName() {
		return this.institutionName;
	}

	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}

	@Column(name = "DUL_VERIFICATION_CODE", length = 8)
	public String getDulVerificationCode() {
		return this.dulVerificationCode;
	}

	public void setDulVerificationCode(String dulVerificationCode) {
		this.dulVerificationCode = dulVerificationCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 120)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED_DATE", length = 7)
	public Date getLastChangedDate() {
		return this.lastChangedDate;
	}

	public void setLastChangedDate(Date lastChangedDate) {
		this.lastChangedDate = lastChangedDate;
	}

	@Column(name = "LAST_CHANGED_BY", length = 120)
	public String getLastChangedBy() {
		return this.lastChangedBy;
	}

	public void setLastChangedBy(String lastChangedBy) {
		this.lastChangedBy = lastChangedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studiesT")
	public Set<DulChecklistSelectionsT> getDulChecklistSelectionsTs() {
		return this.dulChecklistSelectionsTs;
	}

	public void setDulChecklistSelectionsTs(Set<DulChecklistSelectionsT> dulChecklistSelectionsTs) {
		this.dulChecklistSelectionsTs = dulChecklistSelectionsTs;
	}

}
